### ISSUE TITLE
Feedback on Milestone 1

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/student_performance#13]
@YenanZ @zxzzhangg 
Well done on the Milestone 1, your project looks great! Here are some remaining issues:

**About report**
- [x] Do not add Figure numbers and captions as regular text under the figures. You can use `include_graphics()` to read in the figure and add figure caption with `fig.cap` in the chunk options.

**About the main readme**
- [x] Add version information for dependencies

**Suggestions:**
- Update your repository description

**Comment by YenanZ** [comment]
We used include_graphics() to read in figures, we tried to include fig.cap in code chunks but the caption failed to show when we knitted
Version info and repo dscription has been added
