### ISSUE TITLE
Feedbacks from peers

### ISSUE THREAD

**Issue by zxzzhangg** [UBC-MDS/student_performance#16]
Hello, 
I have got two pieces of feedback from my peers.
The first thing is to make the reference part more appropriate.
The second thing is to add more description on why we choose those kinds of visualization.

**Comment by YenanZ** [comment]
Hey , the feedback I got is 
1. We should describe what each subdirectory contains, so the structure of the repo is clear. 
2. The title for the plots are a bit long and too technical
