### ISSUE TITLE
Feedback on proposal

### ISSUE THREAD

**Issue by Nazliozum** [UBC-MDS/student_performance#2]
@zxzzhangg and @YenanZ  , your question is quite interesting and I look forward to reading more on your analysis. Here are some improvement points and minor suggestions for your project.

- Keep in mind that your readme is the landing page for someone examining your analysis. Therefore, you can do some additions that would make the readme more informative and intriguing for a visitor. In particular, you can
	- include a brief introduction about the context and your motivation to do such analysis.
	- explain the data a bit more in detail, state the variables included, or print the head of the data table in the main readme. Including the link to the data source is a good idea, but still explaining the data in your repository is needed.

**Mechanics**

- Your names should not be a part of the project repository name. The name should be more descriptive of the project. For example, simply "student_performance" can be a great name for your project. I would also recommend taking "DSCI_522" out of the name of your project. But if you like it this way, no problem. You should also update your readme title based on the changes you make in the repository title.

- The screenshot of the data import is useful, but I would suggest using a code chunk for the code and printing output as a table. I believe it might look more professional that way. You can do this easily by creating the README file as an R markdown and knitting as github_document.

**Minor Suggestions:**

- Include you Github profile links with your names on the readme.

I hope this feedback is helpful in improving your project. Please let me know if you have any questions. Good luck!

**Comment by YenanZ** [comment]
We have made the above improvements in release v2.0 for milestone 1, thank you for your feedback and encouragement!
